### ISSUE TITLE
Tutorials to create complex flatpak packages

### ISSUE THREAD

**Issue by Kentoseth** [flathub-infra/gsoc#2]
There's many complex GUI apps that could be bundled into flatpak. Many existing ones are bundled, like FreeCAD. But tutorials on how to make them and what each part of the flatpak build-file is doing are not readily available.

**Comment by razzeee** [comment]
I guess you think of this different from https://github.com/flathub-infra/gsoc?tab=readme-ov-file#beginner-tutorials ?

Can you start writing it up?

**Comment by Kentoseth** [comment]
> Can you start writing it up?

I'm actually a beginner myself. I just proposed this suggestion so that it can help other beginners (like me) to create complex packages.

**Comment by razzeee** [comment]
I guess this issue is then okay to be closed, as the readme already has it :)
